add support for qrevo curv
humbertogontijo/python-roborock pull request #253
Opened 2024-12-03 02:19 UTC by Christopher-Masselli

There were some inconsistencies with how Smart Plan was defined in the mappings some were as `custom` with a comment and others were `smart_mode` I just made it all smart_mode for the curv

2024-12-03 03:08 UTC, Lash-L requested changes

2024-12-03 03:08 UTC, Lash-L commented on roborock/code_mappings.py
> -    """Describes the mop mode of the vacuum cleaner."""
Change doesn't seem relevant to your Mr

2024-12-03 03:08 UTC, Lash-L commented
Looks pretty good to me. I unfortunately have a problem with our release pipeline I still need to fix, but I will merge this once I get that fixed

2024-12-18 14:33 UTC, humbertogontijo approved these changes

2024-12-18 14:35 UTC, Lash-L requested changes
I missed that lint is failing. Can you run lint on your branch locally? @Christopher-Masselli 

You don't need to worry about commit lint, as we can fix that when we are merging

2025-01-06 06:40 UTC, allenporter commented
@Christopher-Masselli wanted to give a small poke -- are you able to fix the lint errors?

2025-01-08 04:20 UTC, Lash-L requested changes

2025-01-08 04:20 UTC, Lash-L commented on roborock/code_mappings.py
```suggestion


class RoborockFanSpeedQRevoCurv(RoborockFanPowerCode):
    quiet = 101
    balanced = 102
    turbo = 103
    max = 104
    max_plus = 105
    smart_mode = 110


```

2025-01-08 04:20 UTC, Lash-L commented on roborock/code_mappings.py
> +    smart_mode = 306
```suggestion

class RoborockMopModeQRevoCurv(RoborockMopModeCode):
    standard = 300
    deep = 301
    deep_plus = 303
    fast = 304
    smart_mode = 306

```

2025-01-08 04:20 UTC, Lash-L commented on roborock/code_mappings.py
> +    smart_mode = 209
```suggestion

class RoborockMopIntensityQRevoCurv(RoborockMopIntensityCode):
    off = 200
    low = 201
    medium = 202
    high = 203
    custom_water_flow = 207
    smart_mode = 209

```

2025-01-08 04:20 UTC, Lash-L commented on roborock/containers.py
> +    RoborockMopIntensityQRevoCurv,
```suggestion
    RoborockMopIntensityQRevoCurv,
    RoborockMopIntensityQRevoMaster,
```

2025-01-08 04:20 UTC, Lash-L commented on roborock/containers.py
> +    RoborockFanSpeedQRevoCurv,
```suggestion
    RoborockFanSpeedQRevoCurv,
    RoborockFanSpeedQRevoMaster,
```

2025-01-08 04:20 UTC, Lash-L commented on roborock/containers.py
> +    ROBOROCK_QREVO_CURV,
```suggestion
    ROBOROCK_QREVO_CURV,
    ROBOROCK_QREVO_MASTER,
```

2025-01-08 04:20 UTC, Lash-L commented on roborock/containers.py
> +    mop_mode: RoborockMopModeQRevoCurv | None = None
```suggestion

@dataclass
class QRevoCurvStatus(Status):
    fan_power: RoborockFanSpeedQRevoCurv | None = None
    water_box_mode: RoborockMopIntensityQRevoCurv | None = None
    mop_mode: RoborockMopModeQRevoCurv | None = None

```

2025-01-08 04:29 UTC, Lash-L approved these changes
@humbertogontijo This should be good to merge now - just squash and rename so that commitlint is happy

2025-01-09 15:18 UTC, merged